const EXPOSED_HEADERS = ['x-total-records'];

const PER_PAGE_API_PAGINATION = 10;

const TRANSACTION_TYPES = {
  CREDIT: 'credit',
  DEBIT: 'debit',
  TRANSFER_IN: 'transfer_in',
  TRANSFER_OUT: 'transfer_out',
  WITHDRAWAL: 'withdrawal',
};

const TRANSACTION_STATUS = {
  SUCCESS: 'success',
  FAILED: 'failed',
  FLAGGED: 'flagged',
};

const FRAUD_WINDOW_SECONDS = 5 * 60;
const FRAUD_MAX_HIGH_VALUE_TXNS = 3;
const FRAUD_HIGH_VALUE_RATIO = 0.2;

const RATE_LIMIT_WINDOW_SECONDS = 60;
const RATE_LIMIT_MAX_REQUESTS = 30;

const AUTH_RATE_LIMIT_WINDOW_SECONDS = 60;
const AUTH_RATE_LIMIT_MAX_REQUESTS = 10;

const FX_CACHE_TTL_SECONDS = 6 * 60 * 60;

module.exports = {
  EXPOSED_HEADERS,
  PER_PAGE_API_PAGINATION,
  TRANSACTION_TYPES,
  TRANSACTION_STATUS,
  FRAUD_WINDOW_SECONDS,
  FRAUD_MAX_HIGH_VALUE_TXNS,
  FRAUD_HIGH_VALUE_RATIO,
  RATE_LIMIT_WINDOW_SECONDS,
  RATE_LIMIT_MAX_REQUESTS,
  AUTH_RATE_LIMIT_WINDOW_SECONDS,
  AUTH_RATE_LIMIT_MAX_REQUESTS,
  FX_CACHE_TTL_SECONDS,
};
